### PR TITLE
Crystal 0.32 compatible 

### PR DESCRIPTION
**Pull request by drum445**
Now works with Crystal 0.32, latest kemal and latest crystal-mysql
Deprecation warnings fixed
Changed table schema to now use session_id as primary key
README dependencies update

Cheers

### CODE REVIEW

**Comment by drum445** [comment]
Tests pass, ready to merge please

**Comment by crisward** [comment]
Can you increase the version number / git tag. Just incase there are any legacy users out there (like me!). version `0.2.0` is fine.

Thanks.

**Comment by drum445** [comment]
@crisward version bumped to 0.2.0
Thanks.

**Review by crisward — APPROVED** [review]
Many thanks for updating this.

**Pull request merged**
